### ISSUE TITLE
Undefined method error

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [snmaynard/redis-audit#37]
I'm trying to run the package under ubuntu 14.04 and ruby 1.9.3.
It fails with the following error:
```
Auditing redis://@redis-01.local:6386/ sampling 0 keys
Sampling 601 keys...
./redis-audit.rb:157:in `block (2 levels) in group_key': undefined method `[]' for #<Enumerator:0x0000000289a948> (NoMethodError)
	from ./redis-audit.rb:155:in `each_codepoint'
	from ./redis-audit.rb:155:in `with_index'
	from ./redis-audit.rb:155:in `block in group_key'
	from ./redis-audit.rb:151:in `each'
	from ./redis-audit.rb:151:in `group_key'
	from ./redis-audit.rb:129:in `audit_key'
	from ./redis-audit.rb:98:in `block in audit_keys'
	from ./redis-audit.rb:96:in `times'
	from ./redis-audit.rb:96:in `audit_keys'
	from ./redis-audit.rb:347:in `<main>'

```

**Comment by qhartman** [comment]
I was running into this problem as well. If you pull this revision: https://github.com/snmaynard/redis-audit/archive/aa9296861bafbf43f5db960343c47c13a66de39b.zip

And then comment out the bundle requirement at the top of the redis-audit.rb file it works on 14.04 w. ruby 1.9.3
